"""Deterministic research planning and evidence verification."""

from .query_plan import (
    RESEARCH_LANES,
    QueryPlan,
    QuerySpec,
    ResearchLane,
    SearchRound,
    build_query_plan,
)
from .verification import (
    CREDIBLE_SUPPORT_ROLES,
    VERIFIED_SUPPORT_ROLES,
    ClaimAssessment,
    RoundCompletion,
    SourceCluster,
    StopGate,
    VerificationReport,
    assess_claim,
    build_source_clusters,
    evaluate_stop_gate,
    verify_case,
)
from .factcheck import (
    CLAIM_REVIEW_STATUSES,
    COLLECTION_PROGRESS_STATUSES,
    FactcheckError,
    IDENTITY_STATUSES,
    QUOTE_STATUSES,
    QuoteCheck,
    build_factcheck_report,
    build_identity_candidates,
    check_quote,
    evaluate_collection_coverage,
    load_local_sources,
    write_factcheck_report,
)

__all__ = [
    "RESEARCH_LANES",
    "CREDIBLE_SUPPORT_ROLES",
    "VERIFIED_SUPPORT_ROLES",
    "ClaimAssessment",
    "QueryPlan",
    "QuerySpec",
    "ResearchLane",
    "RoundCompletion",
    "SearchRound",
    "SourceCluster",
    "StopGate",
    "VerificationReport",
    "assess_claim",
    "build_query_plan",
    "build_source_clusters",
    "evaluate_stop_gate",
    "verify_case",
    "FactcheckError",
    "CLAIM_REVIEW_STATUSES",
    "COLLECTION_PROGRESS_STATUSES",
    "IDENTITY_STATUSES",
    "QUOTE_STATUSES",
    "QuoteCheck",
    "build_factcheck_report",
    "build_identity_candidates",
    "check_quote",
    "evaluate_collection_coverage",
    "load_local_sources",
    "write_factcheck_report",
]
